---
abstract: 'Panda blog orientated markup'
author:
  - 'J Gregory <john@johngregory.me.uk>'
build_requires:
  Test::Exception: 0.32
  Test::More: 0.99
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Caffeinated_Markup_Language
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Escape: 1.08
  Log::Log4perl: 1.42
  Moo: 1.003001
  Readonly: 1.03
  boolean: 0.30
version: v0.11.1
